"""Build composition/assets/data.js: narration word timings (composition time),
IVR words, and per-frame RMS envelopes (IVR, music) for the audio-reactive bits.
Stdlib only; needs ffmpeg on PATH. Run from anywhere."""
import json, math, os, subprocess, array

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..', '..', '..', '..'))
AUD = os.path.join(ROOT, 'docs', 'launch', 'audio')
COMP = os.path.join(HERE, '..', 'composition')
FPS = 30

# composition timing (seconds) — keep in sync with index.html
T = {
    'l1': 0.20, 'l2': 2.60, 'l3': 6.95, 'l4': 10.20, 'l5': 13.45, 'l6': 22.30,
    'ivr_start': 3.60, 'ivr_media': 6.70, 'ivr_end': 6.95,
    'music_start': 6.84, 'music_media': 0.50, 'end': 25.90,
}
L5_RATE = 1.1

def words(cid, offset, rate=1.0):
    with open(os.path.join(AUD, cid + '.words.json'), encoding='utf-8') as f:
        w = json.load(f)
    return [{'w': x['w'], 's': round(offset + x['start'] / rate, 3), 'e': round(offset + x['end'] / rate, 3)} for x in w]

def rms_env(path, media_start, dur, sr=8000):
    raw = subprocess.run(['ffmpeg', '-v', 'error', '-ss', str(media_start), '-t', str(dur), '-i', path,
                          '-ac', '1', '-ar', str(sr), '-f', 's16le', '-'], capture_output=True, check=True).stdout
    a = array.array('h'); a.frombytes(raw[: len(raw) // 2 * 2])
    hop = sr // FPS
    out = []
    for i in range(0, len(a), hop):
        seg = a[i:i + hop]
        if not seg: break
        out.append(math.sqrt(sum(v * v for v in seg) / len(seg)))
    peak = max(out) or 1
    return [round(v / peak, 3) for v in out]

data = {
    'T': T,
    'cap': {
        'l1': words('nar_l1', T['l1']),
        'l2': words('nar_l2', T['l2']),
        'l3': words('nar_l3', T['l3']),
        'l4': words('nar_l4', T['l4']),
        'l5': words('nar_l5', T['l5'], L5_RATE),
        'l6': words('nar_l6', T['l6']),
    },
    'ivr': [w for w in words('ivr_de', T['ivr_start'] - T['ivr_media']) if w['s'] < T['ivr_end'] and w['e'] > T['ivr_start']],
    'ivrRms': rms_env(os.path.join(AUD, 'ivr_de.mp3'), T['ivr_media'], T['ivr_end'] - T['ivr_start']),
    'musicRms': rms_env(os.path.join(COMP, 'assets', 'music', 'happy-beats-business-moves-vol-12-by-ende-dot-app.mp3'),
                        T['music_media'], T['end'] - T['music_start']),
}
with open(os.path.join(COMP, 'assets', 'data.js'), 'w', encoding='utf-8') as f:
    f.write('/* generated by tools/build_data.py */\nwindow.ANK = ' + json.dumps(data, ensure_ascii=False) + ';\n')
print('ok', len(data['ivrRms']), len(data['musicRms']), len(data['ivr']))
